In [1]:
import numpy as np

In [2]:
def array_info(array: np.ndarray) -> None:
    print(f"ndim: {array.ndim}")
    print(f"shape: {array.shape}")
    print(f"size: {array.size}")
    print(f"dtype: {array.dtype}")
    print(f"values:\n{array}\n")

In [4]:
my_np_array = np.array([1, 4, 2, 5.2, 3])
array_info(my_np_array)

ndim: 1
shape: (5,)
size: 5
dtype: float64
values:
[1.  4.  2.  5.2 3. ]



In [9]:
my_np_array = np.array([1, 2, 3, 4], dtype='float32', shape=(2,2))
array_info(my_np_array)

TypeError: 'shape' is an invalid keyword argument for array()

In [11]:
my_np_array = np.ones(shape=(3, 6), dtype=float)
array_info(my_np_array)

ndim: 2
shape: (3, 6)
size: 18
dtype: float64
values:
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]



In [12]:
my_np_array = np.full(shape=(3, 5), fill_value=7)
array_info(my_np_array)

ndim: 2
shape: (3, 5)
size: 15
dtype: int32
values:
[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]



In [13]:
my_np_array = np.eye(N=4)
array_info(my_np_array)

ndim: 2
shape: (4, 4)
size: 16
dtype: float64
values:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]



In [14]:
my_np_array = np.diag([1, 4, 11,50])
array_info(my_np_array)

ndim: 2
shape: (4, 4)
size: 16
dtype: int32
values:
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0 11  0]
 [ 0  0  0 50]]



In [17]:
my_np_array = np.random.randint(low=0, high=10, size=(3, 3))
array_info(my_np_array)

ndim: 2
shape: (3, 3)
size: 9
dtype: int32
values:
[[4 8 7]
 [9 6 9]
 [8 7 9]]



In [19]:
my_np_array = np.random.random(size=(3, 3))
array_info(my_np_array)

ndim: 2
shape: (3, 3)
size: 9
dtype: float64
values:
[[0.92627227 0.47566754 0.35116475]
 [0.99016029 0.27704445 0.85732914]
 [0.92548082 0.88359851 0.07521903]]



In [20]:
x = np.array([[1, 2], [3, 4], [5, 6]])

array_info(x)

ndim: 2
shape: (3, 2)
size: 6
dtype: int32
values:
[[1 2]
 [3 4]
 [5 6]]



In [25]:
print(x[0][1])

2


In [28]:
print(x[::-1])

[[5 6]
 [3 4]
 [1 2]]


In [31]:
mean = [0, 0]
cov = [[1, 2],
       [2, 5]]

x = np.random.multivariate_normal(mean=mean, cov=cov, size=10)

print(x)
print(x.shape)

[[ 3.33199465  6.85393505]
 [-0.42321723  0.26428552]
 [ 0.07300731 -1.78768608]
 [ 0.65669145  1.42152246]
 [ 1.48595703  1.12556272]
 [ 0.07024413 -1.26838168]
 [ 1.45422599  2.32794647]
 [-0.88559452 -1.08417101]
 [-0.79476365 -1.79103151]
 [ 0.18689206  1.78829177]]
(10, 2)


In [35]:
rand_idxs = np.random.randint(low=0, high=x.shape[0], size=3)

print(rand_idxs)

[1 1 2]


In [36]:
x_subsample = x[rand_idxs]

print(x_subsample)

[[-0.42321723  0.26428552]
 [-0.42321723  0.26428552]
 [ 0.07300731 -1.78768608]]


In [37]:
print(x)

[[ 3.33199465  6.85393505]
 [-0.42321723  0.26428552]
 [ 0.07300731 -1.78768608]
 [ 0.65669145  1.42152246]
 [ 1.48595703  1.12556272]
 [ 0.07024413 -1.26838168]
 [ 1.45422599  2.32794647]
 [-0.88559452 -1.08417101]
 [-0.79476365 -1.79103151]
 [ 0.18689206  1.78829177]]


In [38]:
x_sub_array = x[2:4,:]
print(x_sub_array)

[[ 0.07300731 -1.78768608]
 [ 0.65669145  1.42152246]]


In [39]:
x_sub_array[0, 0] = -1

array_info(x_sub_array)

ndim: 2
shape: (2, 2)
size: 4
dtype: float64
values:
[[-1.         -1.78768608]
 [ 0.65669145  1.42152246]]



In [40]:
print(x_sub_array)

[[-1.         -1.78768608]
 [ 0.65669145  1.42152246]]


In [41]:
print(x)

[[ 3.33199465  6.85393505]
 [-0.42321723  0.26428552]
 [-1.         -1.78768608]
 [ 0.65669145  1.42152246]
 [ 1.48595703  1.12556272]
 [ 0.07024413 -1.26838168]
 [ 1.45422599  2.32794647]
 [-0.88559452 -1.08417101]
 [-0.79476365 -1.79103151]
 [ 0.18689206  1.78829177]]


In [42]:
x_copy = x[:2, :2].copy()

array_info(x_copy)

ndim: 2
shape: (2, 2)
size: 4
dtype: float64
values:
[[ 3.33199465  6.85393505]
 [-0.42321723  0.26428552]]



In [47]:
a = np.arange(start=1, stop=10)
array_info(a)

ndim: 1
shape: (9,)
size: 9
dtype: int32
values:
[1 2 3 4 5 6 7 8 9]



In [54]:
x = np.array([1, 2, 3, 4])

array_info(x)

ndim: 1
shape: (4,)
size: 4
dtype: int32
values:
[1 2 3 4]



In [51]:
x = np.reshape(x, newshape=(1, 3))

array_info(x)

ndim: 2
shape: (1, 3)
size: 3
dtype: int32
values:
[[1 2 3]]



In [65]:
array_info(x)

x = x.reshape((2, 2))

array_info(x)

ndim: 1
shape: (4,)
size: 4
dtype: int32
values:
[1 2 3 4]

ndim: 2
shape: (2, 2)
size: 4
dtype: int32
values:
[[1 2]
 [3 4]]



In [64]:
array_info(x)

x = x.ravel()

array_info(x)

ndim: 3
shape: (2, 2, 1)
size: 4
dtype: int32
values:
[[[1]
  [2]]

 [[3]
  [4]]]

ndim: 1
shape: (4,)
size: 4
dtype: int32
values:
[1 2 3 4]



In [66]:
x = x.reshape((2, 2))
array_info(x)

x = x.flatten()

array_info(x)

ndim: 2
shape: (2, 2)
size: 4
dtype: int32
values:
[[1 2]
 [3 4]]

ndim: 1
shape: (4,)
size: 4
dtype: int32
values:
[1 2 3 4]



In [67]:
print('hallo')

hallo
